---
title: "732A62 Lab 1"
author: "Emil K Svensson & Rasmus Holm"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 1 

```{r}

t <- 0:99 
ts1 <- rep(0,100)

set.seed(12345)
for (i in 3:100){ 
  ts1[i] <- -0.8*ts1[i-2] + rnorm(1,0,1) 
}

ts2 <- cos( 2*pi*t / 5)



vt1 <- rep(0,100)
vt2 <- rep(0,100)

for (i in 1:100){
  if (i == 1){
    vt1[i] <- 0.2 * ts1[i]
    vt2[i] <- 0.2 * ts2[i]

  }
  
   if (i == 2){
    vt1[i] <- 0.2 *(ts1[i-1] + ts1[i])
    vt2[i] <- 0.2 *(ts2[i-1] + ts2[i])
   }
  
    if (i == 3){
    vt1[i] <- 0.2 *(ts1[i] + ts1[i-1] + ts1[i-2])
    vt2[i] <- 0.2 *(ts2[i] + ts2[i-1] + ts2[i-2])
   }
  
  if (i == 4){
    vt1[i] <- 0.2 *(ts1[i] + ts1[i-1] + ts1[i-2] + ts1[i-3])
    vt2[i] <- 0.2 *(ts2[i] + ts2[i-1] + ts2[i-2] + ts2[i-3])
   }
  
  if (i >= 5){
    vt1[i] <- 0.2 *(ts1[i] + ts1[i-1] + ts1[i-2] + ts1[i-3] + ts1[i-4])
    vt2[i] <- 0.2 *(ts2[i] + ts2[i-1] + ts2[i-2] + ts2[i-3] + ts2[i-4])
  }
  
}

par(mfrow = c(2,2))
plot(ts1,type = "l", main = "ts1")
plot(ts2, type = "l", main = "ts2")
plot(vt1,type = "l", main = "vt1")
plot(vt2, type = "l", main = "vt2")
par(mfrow = c(1,1))


acf

filter(0:3,c(-0.8,2))
```


# Assignment 2

```{r}
rhine <- read.csv2("../data/Rhine.csv")

rhine <- ts(rhine)

rhine

plot(y = rhine[,4], x = rhine[,3], type = "l")
# abline(lm(rhine[,4] ~ rhine[,3], data = rhine))
# lines(predobj$fit + 1.96*predobj$se.fit ~ as.numeric(rhine[,3]))
# lines(predobj$fit - 1.96*predobj$se.fit ~ as.numeric(rhine[,3]))




x <- rhine[,4]
old <- par(mfrow = c(3,4))
for (i in 1:12){ 
 plot(lag(x,i),x)
}
par(old)
```


```{r}
lmobj<-lm(rhine[,4] ~ rhine[,3], data = rhine)
res1 <- residuals(lmobj)
summary(lmobj)


acf(res1)
plot(res1)
abline(h = 0, col = "blue", lwd =2)
predobj<- predict(lmobj, se.fit = TRUE)
```


```{r}
plot(x = rhine[,3], y= rhine[,4], type = "l", lwd =2)
lines(ksmooth(y=rhine[,4], x = rhine[,3], bandwidth = 5), col = "blue", lwd = 2.25, lty =2)


kersmo <- ksmooth(y=rhine[,4], x = rhine[,3], bandwidth = 5)

kerres <- kersmo$y - rhine[,4]

plot(kerres, type = "p")
abline(h = 0, col = "blue", lwd = 2)

acf(kerres)


```


```{r}

month.f <- as.factor(rhine[,2])
dummyfit <- as.data.frame(model.matrix(rhine[,4]~ rhine[,3]+month.f))[,-1]
dumlm <- lm(rhine[,4]~.,dummyfit)

plot(resid(dumlm))
abline(h = 0, col = "blue", lwd=2)
acf(resid(dumlm))

```

```{r}
library(MASS)
stepAIC(dumlm,direction = "backward", steps = 1000)
```



# Assignment 3 

```{r}

library(astsa)

plot(oil,col = "blue", ylim = c(0,400))
lines(gas,col = "red")

loil <- log(oil)
lgas <- log(gas)

plot(loil,col = "blue", ylim = c(2,6))
lines(lgas,col = "red")
```


```{r}
dloil<-diff(loil)
dlgas<-diff(lgas)

plot(dloil,col = "blue", ylim = c(-0.3,0.4), lwd = 2)
lines(dlgas,col = "red", lty = 2, lwd = 1.25)

acf(dloil)
acf(dlgas)
```


```{r}
xt <- dloil
yt <- dlgas

par(mfrow = c(2,2))
plot(x = xt, y = yt )
plot(x = xt, y = lag(yt,1) )
plot(x = xt, y = lag(yt,2) )
plot(x = xt, y = lag(yt,3) )
par(old)
```

