---
title: "732A62 Lab 2"
author: "Emil K Svensson & Rasmus Holm"
date: "`r Sys.Date()`"
output:
    pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 1

# a)

```{r}
library(astsa)
library(kernlab)
library(TSA)
library(forecast)

set.seed(12345)
AR3 <- arima.sim(1000, model = list(order = c(3,0,0),
                                    ar = c(0.8, -0.2, 0.1)))

## The theoretical
AR3.pacf <- pacf(AR3, plot=F)
AR3.data <- ts.intersect(xt = AR3, x1 = lag(AR3, 1), x2 =lag(AR3, 2), x3= lag(AR3, 3))

AR.lm <- resid(lm(xt ~ x1 + x2, data = AR3.data))
AR.lm.lag3 <- resid(lm(x3 ~ x1 + x2 , data = AR3.data))

AR3.pacf[3]
cor(AR.lm, AR.lm.lag3)
```

# b)

```{r}
set.seed(12345)
AR2 <- arima.sim(100, model = list(order = c(2,0,0),
                                   ar = c(0.8, 0.1)))

ar2.yw <- ar(AR2, order.max = 2, method = "yw", aic = FALSE)
ar2.ols <- ar(AR2, order.max = 2, method = "ols", aic = FALSE)
ar2.mle <- arima(AR2, order = c(2,0,0), method = "ML")

ar2.yw
ar2.ols
ar2.mle
```

Yes, the theoretical value for $$\phi_2$$ is inside the confidence-intervall for the ML estimate.

# c)

```{r}
set.seed(12345)
ma.coef <- c(0.3, rep(0, 10), 0.6)
ts4 <- arima.sim(n=200, model=list(order=c(0, 0, 12), ma = ma.coef))

theoretical.acf <- ARMAacf(ma=c(ma.coef, 0.3 * 0.6))
theoretical.pacf <- ARMAacf(ma=c(ma.coef, 0.3 * 0.6), pacf=TRUE)

plot(theoretical.acf, type="h", main="Theoretical ACF")
abline(h=0)

plot(theoretical.pacf, type="h", main="Theoretical PACF")
abline(h=0)

empirical.acf <- acf(ts4)
empirical.pacf <- pacf(ts4)
```

# d)

```{r}
set.seed(12345)
ma.coef <- c(0.3, rep(0, 10), 0.6)
ts5 <- arima.sim(n=200, model=list(order=c(0, 0, 12), ma = ma.coef))


ts5.fit <- arima(ts5, order=c(0, 0, 1), seasonal=list(order=c(0, 0, 1), period=12))
ts5.pred <- predict(ts5.fit, n.ahead=30, se.fit=TRUE)

plot(ts(c(ts5, ts5.pred$pred)), ylim=c(-4, 4))
lines(200 + 1:length(ts5.pred$pred), ts5.pred$pred + 1.96 * ts5.pred$se, lty=2, col="red")
lines(200 + 1:length(ts5.pred$pred), ts5.pred$pred - 1.96 * ts5.pred$se, lty=2, col="red")

## gausspr.data <- ts.intersect(x=ts5, x1=lag(ts5, 1), x12=lag(ts5, 12), x13=lag(ts5, 13))
## gausspr.fit <- gausspr(x ~ ., gausspr.data)
## plot(ts5)
## lines(fitted(gausspr.fit), col="red", lwd=2)

gausspr.data <- data.frame(y=ts5, x=1:200)
gausspr.fit <- gausspr(y ~ x, gausspr.data)
gausspr.pred <- predict(gfit, data.frame(x=201:230))

plot(ts5, xlim=c(0, 230))
lines(c(fitted(gausspr.fit), gausspr.pred), , col="red")
```

# e)

```{r}
set.seed(12345)
ts6 <- arima.sim(model=list(ma=c(0.5), ar=c(0.7)), n=50)

train <- ts(ts6[1:40])
test <- ts(ts6[41:50])

ts6.fit <- arima(train, order=c(1, 0, 1), include.mean = F)
ts6.pred <- predict(ts6.fit, n.ahead=10)

plot(ts(c(train, test)), ylim=c(-4, 7), type="l")
lines(40 + 1:length(test), ts6.pred$pred, col="blue")
lines(40 + 1:length(test), ts6.pred$pred + 1.96 * ts6.pred$se, lty=2, col="red")
lines(40 + 1:length(test), ts6.pred$pred - 1.96 * ts6.pred$se, lty=2, col="red")

plot(40 + 1:length(test), test, ylim=c(-4, 7), xlim=c(40, 50), type="p")
points(40 + 1:length(test), ts6.pred$pred, col="blue")
lines(40 + 1:length(test), ts6.pred$pred + 1.96 * ts6.pred$se, lty=2, col="red")
lines(40 + 1:length(test), ts6.pred$pred - 1.96 * ts6.pred$se, lty=2, col="red")
```

\newpage

# Assignment 2

```{r}
assignment2 <- function(data){
    old <- par(mfrow = c(2, 2))
    acf(data, lag.max = 40)
    pacf(data, lag.max = 40)
    acf(diff(data, lag = 1), lag.max = 40)
    pacf(diff(data, lag = 1), lag.max = 40)
    par(old)
}
```

## Chicken

```{r}
assignment2(chicken)
```

## so2

```{r}
assignment2(so2)
```

## EQcount

```{r}
assignment2(EQcount)
```

## HCT

```{r}
assignment2(HCT)
```

\newpage

# Assignment 3

```{r}
plot_helper <- function(data, title) {
    old <- par(mfrow=c(4, 1))
    plot(data, main=title)
    acf(data, lag.max=40, main="")
    pacf(data, lag.max=40, main="")
    qqnorm(data, main="", las=1)
    qqline(data)
    par(old)
}

test_helper <- function(data) {
    print(Box.test(data, lag = 1, type = "Ljung-Box"))
    print(suppressWarnings(adf.test(data)))
    e <- eacf(data)
}

fit_plot <- function(model) {
    pred <- predict(model, n.ahead=20, se.fit=TRUE)
    upper_band <- pred$pred + 1.96 * pred$se
    lower_band <- pred$pred - 1.96 * pred$se

    plot(c(model$x, pred$pred), type="l", xlim=c(500, length(oil) + 20), ylim=c(min(lower_band), max(upper_band)))
    lines(length(oil) + 1:20, upper_band, lty=2, col="red")
    lines(length(oil) + 1:20, lower_band, lty=2, col="red")
}
```

## a)

```{r}
loil <- log(oil)
doil <- diff(oil)
ddoil <- diff(oil, 2)
dloil <- diff(loil)
ddloil <- diff(loil, 2)
```

\newpage

```{r, echo=FALSE, fig.height=10}
plot_helper(oil, "Oil")
```

```{r, echo=FALSE, fig.height=10}
plot_helper(doil, "1 Difference Oil")
```

```{r, echo=FALSE, fig.height=10}
plot_helper(ddoil, "2 Difference Oil")
```

```{r, echo=FALSE, fig.height=10}
plot_helper(dloil, "1 Difference log Oil")
```

```{r, echo=FALSE, fig.height=10}
plot_helper(ddloil, "2 Difference log Oil")
```

\newpage

```{r}
test_helper(doil)
test_helper(ddoil)
test_helper(dloil)
test_helper(ddloil)
```

\newpage

```{r}
fit1 <- Arima(loil, order=c(0, 2, 1))
fit1

fit_plot(fit1)
```

```{r}
fit2 <- Arima(loil, order=c(0, 1, 3))
fit2

fit_plot(fit2)
```

\newpage

```{r, fig.height=10, echo=FALSE}
old <- par(mfrow=c(4, 1))
plot(oil, main="Oil")
plot(diff(oil), main="Difference 1 Oil")
plot(dloil, main="Difference 1 Log Oil")
plot(ddloil, main="Difference 2 Log Oil")
par(old)
```

Clearly difference log is the data we should work with. bla, bla, ...


```{r, fig.height=10, echo=FALSE}
old <- par(mfrow=c(4, 1))
acf(dloil, lag.max=40, main="Difference 1 Log Oil ACF")
pacf(dloil, lag.max=40, main="Difference 1 Log Oil PACF")
acf(ddloil, lag.max=40, main="Difference 2 Log Oil ACF")
pacf(ddloil, lag.max=40, main="Difference 2 Log Oil PACF")
par(old)
```

```{r}
eacf(dloil)
eacf(ddloil)
```

```{r, fig.height=10, echo=FALSE}
old <- par(mfrow=c(2, 1))
qqnorm(dloil, main="Difference 1 Log Oil", las=1)
qqline(dloil, main="")
qqnorm(ddloil, main="Difference 2 Log Oil", las=1)
qqline(ddloil, main="")
par(old)
```

\newpage

```{r}
fit1 <- Arima(loil, order=c(1, 1, 1))
fit1
fit2 <- Arima(loil, order=c(0, 1, 3))
fit2
fit3 <- Arima(loil, order=c(0, 2, 1))
fit3
```

\newpage

```{r}
complex_dist <- function(x) {
    sqrt(Re(x)^2 + Im(x)^2)
}

sapply(polyroot(c(1, -2, 1)), complex_dist)
sapply(polyroot(c(1, -1)), complex_dist)
```

```{r}
fit_plot(fit3)
```

\newpage

## b)
