---
title: "732A62 Lab 3"
author: "Emil K Svensson & Rasmus Holm"
date: "`r Sys.Date()`"
output:
    pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 1

## 1)

```{r}
library(astsa)
library(TSA)
library(forecast)
library(fGarch)

plot(chicken)
```

It looks like a linear, potentially quadratic, trend.

## 2)

```{r}
lm_data <- data.frame(chicken=chicken, time=1:length(chicken))
lm_fit <- lm(chicken ~ time, lm_data)
z <- resid(lm_fit)
plot(z, type="l", ylab="resid", xlab="Time")
```

The residuals do not look stationary.

## 3)

```{r}
denom <- sqrt(length(z)) *
    exp(complex(imaginary=2 * pi * 0:(length(z) - 1) / length(z)))
density <- fft(z) / denom
periodigram <- abs(density)^2

upper <- 2 * mean(periodigram) / qchisq(0.025, 2)
lower <- 2 * mean(periodigram) / qchisq(0.975, 2)

plot(periodigram, type="o")
abline(h=lower, col="red", lwd=2)
```

## 4)

```{r}
freq_density <- density
freq_density[periodigram < lower] <- 0

n <- length(z)
ts <- 1:(n + 36)

xs <- rep(0, n + 36)

for (t in ts) {
    xs[t] <- sum(freq_density * exp(complex(imaginary=2 * pi * (0:(n - 1)) / n * t))) / sqrt(n)
}

plot(z, type="l")
lines(Re(xs), col="red")
```

## 5)

```{r}

k <- kernel("modified.daniell", c(2,2))
md_dan<- mvspec(z, kernel=k, log="no") 
plot(md_dan$spec)
md_dan$freq

Lh <- md_dan$Lh

lower1<- 2 * Lh * md_dan$spec / qchisq(0.975,2*Lh)
upper1<- 2 * Lh * md_dan$spec / qchisq(0.025,2*Lh)

plot(x = md_dan$freq, y = md_dan$spec, type = "o")
lines(x = md_dan$freq, y = lower1 , col = "blue")
lines(x = md_dan$freq, y = upper1 , col = "blue")


# Comparing frequencies 

md_dan$freq[md_dan$freq < 0.1]

freq_4 <- 0:179/180
freq_4[periodigram > lower]
```


## 6)

```{r}
fit_plot <- function(model, data) {
    nahead <- 36
    pred <- predict(model, n.ahead=nahead, se.fit=TRUE)
    upper_band <- pred$pred + 1.96 * pred$se
    lower_band <- pred$pred - 1.96 * pred$se

    n <- length(data)

    plot(c(data, pred$pred), type="l",
         xlim=c(n - nahead, n + nahead),
         ylim=c(min(lower_band), max(upper_band)), ylab="Value", xlab="Time")
    lines(n + 1:nahead, upper_band, lty=2, col="red")
    lines(n + 1:nahead, lower_band, lty=2, col="red")
}
```

```{r}
fit <- arima(chicken, order=c(2, 1, 0), seasonal=list(order=c(0, 0, 1), period=12))
fit_plot(fit, chicken)
```

## 7)

```{r}
fit <- arima(chicken, order=c(3, 0, 0), seasonal=list(order=c(0, 0, 1), period=12))
fit_plot(fit, chicken)
```

\newpage

# Assignment 2

## 1)

```{r}

ld_oil <-diff(log(oil))

z <-ld_oil[1:(52*9 + 33)]

old <- par(mfrow = c(1,2))
acf(z)
pacf(z)
par(old)

suggested_model <- Arima(z, order = c(3,0,0))

summary(suggested_model)

r <- resid(suggested_model)
```

## 2)

```{r}
plot(r)
old <- par(mfrow = c(1,2))
acf(r^2)
pacf(r^2)
par(old)


fit1<- garchFit(~ arma(3,0) + garch(1,0) , data = ld_oil, trace = FALSE)
fit1
```
The time series of the residuals seem to have an increasing variance in the end of the residuals.

The ACF of the squared residuals trails of and in the PACF they cuts of after 2 lags. Indicating a GARCH(p,q)
 An p = 2, q = 0 maybe?
## 3)

```{r}


helper <- function(data){
acf(data)
acf(data^2)
qqnorm(data)
qqline(data)

}


helper(fit1@residuals)
fit1@fit$objective

```

## 4)

```{r}

```

## 5)

```{r}

```

## 6)

```{r}

```
